feat: добавлены классы Film и User, контроллеры, валидаторы и тесты
BiryulevaIrina/java-filmorate pull request #2
Opened 2023-04-24 18:02 UTC by BiryulevaIrina

2023-04-24 19:41 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-04-24 19:41 UTC, FanaticFiz commented on pom.xml
> +	<properties>
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ResponseBody
Аннотация `RestController` уже включает в себя `ResponseBody` поэтому последняя тут лишняя.

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("Ошибка: проверьте заполнение полей запроса.");
Все верно, но нужно не только в лог это записать, но и клиенту ответить правильно! 
И это нужно сделать с помощью исключений. 
Вот ниже ты так и делаешь, бросаешь `ValidationException`

Вот только класс нужно назвать по другому.
`ValidationException -> BadRequestException` - более обще.

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Фильма с таким идентификатором нет в базе");
Если мы хотим сказать что чего-то нет, то для клиента мы должны возвращать код 404, а это NOT_FOUND и это второе исключение, которое должно быть у тебя: `NotFoundException`

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(id, user);
Где то потерялась логика из ТЗ - `имя для отображения может быть пустым — в таком случае будет использован логин;`

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public Boolean getIsValid(Film film) {
По поводу названия...
Ну для начала вот так `get` и `is` вместе не пишут никогда.

`isValid` - это норма.

Но, у тебя не и в логике валидатора мешанина ты и кидаешься исключениями и возвращаешь значение. Не смешивай эти два подхода.
Или кидайся исключениями и называй свой метод соответствующе: `throwIfNotValid`
Или не используй исключений тут, но возвращать надо объект с описанием того в каком поле что сломано - это сложнее.

2023-04-24 19:41 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать. Как мини задание: разберись как задать порт для сервиса отличный от дефолтного, и как задать чтобы порт был случайным.(Менять порт на другой не нужно, для тестов нужен именно 8080)

2023-04-25 10:24 UTC, BiryulevaIrina commented on pom.xml
> +	<properties>
pom файл причесала, кодировку указала

2023-04-25 10:24 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ResponseBody
Да убедилась в этом, ResponseBody убрала.

2023-04-25 10:25 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("Ошибка: проверьте заполнение полей запроса.");
Выполнено!

2023-04-25 10:26 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(id, user);
Перенесла логику из валидатора в контроллер. Проверила тестами.

2023-04-25 10:27 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public Boolean getIsValid(Film film) {
Исправила метод в обоих контроллерах, в том числе наименование, убрала переменную isValid. Проверила тестами.

2023-04-25 10:28 UTC, BiryulevaIrina commented on src/main/resources/application.properties
> +
Переименовала файл

2023-04-25 19:01 UTC, FanaticFiz approved these changes

2023-04-25 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Этот код написан дважды!
И при создании и при обновлении...

2023-04-26 09:42 UTC, merged