feat: добавлены хранилища, сервисы, возм добавления и удаления друзей и лайков
BiryulevaIrina/java-filmorate pull request #3
Opened 2023-05-10 16:55 UTC by BiryulevaIrina

2023-05-10 20:17 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    ;
Дай угадаю... Это кот на клавиатуру прыгнул!? )))

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> findAll() {
`Collection -> List`
List более ходовой интерфейс

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getPopularFilms(int count) {
Ты даже приводишь все к List -> `Collectors.toList()`
Вот и возвращай List.

Но тут проблема еще и не в этом...
Работу по поиску отсортированных по популярности фильмов стоит переложить на хранилище. На следующей итерации ты с этим будешь справляться запросом в БД.

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NotFoundException("Не найден пользователь с ID = " + userId);
Тут твоё сообщение о том что пользователь не найден сбивает с толку, будь точнее!

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film findFilmById(int userId);
findFilmById -> findById

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(film.getId())) {
Проверять есть фильм или нет и кидать исключение, нужно в сервисе!
Метод добавления в хранилище должен только добавлять.

2023-05-10 20:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NotFoundException("Не найден фильм с ID = " + filmId);
Как и тут... проверять и кидать исключение надо в сервисе.
Метод в хранилище должен только достать фильм.

Причем удобно будет возвращать не голый фильм а `Optional<Film>`
У `Optional` есть удобные методы, для написания кода в одну строку в функциональном стиле, попробуй применить, а я помогу...

2023-05-11 19:02 UTC, BiryulevaIrina commented
Внесла правки в соответствии с замечаниями. Валидация добавлена в контроллеры. Проверки и исключения в сервисах

2023-05-12 08:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkUserName(User user) {
Название метода как бы не подразумевает что ты будешь что-то менять...
Надо подобрать более удачное название

2023-05-12 08:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findAll().contains(film)) {
Не правильно делать `findAll().contains(film)` в сервисе.
Лучше из репозитория выставить метод с названием `isExist`, например. 
Или воспользоваться уже существующим `findById`.

Выбирать все сущности зло - с их ростом наш сервис будет деградировать.

2023-05-13 08:39 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Optional<User> delete(int userId);
Вернула предыдущую версию метода

2023-05-13 08:40 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkUserName(User user) {
Переименовала метод на userNameVerification

2023-05-13 08:41 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findAll().contains(film)) {
Над этим вопросом буду думать...

2023-05-13 08:47 UTC, merged