feat: подключение базы данных
BiryulevaIrina/java-filmorate pull request #4
Opened 2023-05-18 17:10 UTC by BiryulevaIrina

2023-05-18 18:24 UTC, MsHitai commented on README.md
> +![Filmorate diagram ](https://github.com/BiryulevaIrina/java-filmorate/assets/120193162/6ef6c8af-94dd-4c99-939d-af41ea26c5ad)
Мне кажется, что в таблице friends возможно лишним будет ключ id_user, потому что его можно получить из таблицы users по ключу id_friend. Понравилась идея с отдельной таблицей likes. Но есть небольшое сомнение на счет того, что каждый раз нужно считать сколько лайков путем подсчета юзеров, а если их миллион - то это возможно уже не такая быстрая операция. Возможно стоит добавить в нее "total", как количество лайков?

В остальном все отлично, запросы правильные!

2023-06-05 18:51 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    email    VARCHAR(55) NOT NULL UNIQUE,
Ну это же очень мало 55 символов... И для email, и для name

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage, LikeDao likeDao, GenreDao genreDao, MpaRatingDao mpaRatingDao) {
Строка не должна быть длиннее 120 символов. Делаем переносы.

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Film film : films) {
Тут нужно быть аккуратнее!

Вот так в лоб нельзя делать в данном случае!
Давай поясню...
пусть у нас есть 100 фильмов... а у каждого из них есть жанры
для того чтобы собрать всё в одно и отдать при запросе нам нужно:

- достать все фильмы
- и все жанры к ним

Если делать "в лоб" то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры...
получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....

Это называется проблема `N+1`
Чтобы её избежать мы должны заморочиться и в итоге приходим к всего ДВУМ запросам, вместо 101 !

Первый запрос на все фильмы, второй на все жанры для этих фильмов.

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> filmOptional = filmStorage.findById(filmId);
Вот пример кода, как стоит пользоваться Optional и методом orElseThrow

```
    public Film findById(int filmId) {
        Film film = filmStorage.findById(filmId)
                               .orElseThrow(() -> new NotFoundException("Фильма с id " + filmId + " нет в базе."));

        film.setGenres(genreDao.getGenres(filmId));
        film.setMpa(mpaRatingDao.getByFilmId(filmId));
        
        return film;
    }
```

Переработай код в других местах.

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public List<Genre> findAll() {
Давай разделять по глаголам. В dao - `find`, а в сервисах - `get`

2023-06-05 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setId(++id);
id может и должно генерироваться базой автоматически, почему мы до сих пор делаем  ++id?

2023-06-07 11:31 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Film film : films) {
Сделан метод в GenreDao, в котором получаем одним запросом все жанры по переданным идентификаторам фильмов. Вызываю данный метод в сервисе фильмов в setGenre. Жанры неправильно подтягиваются.

2023-06-07 11:35 UTC, BiryulevaIrina commented on src/main/resources/schema.sql
> +    email    VARCHAR(55) NOT NULL UNIQUE,
Исправлено

2023-06-07 11:35 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage, LikeDao likeDao, GenreDao genreDao, MpaRatingDao mpaRatingDao) {
Исправлено

2023-06-07 11:35 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> filmOptional = filmStorage.findById(filmId);
Переработан

2023-06-07 11:36 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public List<Genre> findAll() {
Выполнено

2023-06-07 11:37 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setId(++id);
Не проходят тесты постман без ++id

2023-06-08 04:36 UTC, FanaticFiz approved these changes

2023-06-08 04:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDaoImpl.java
> +                        new GenreMapper(), id)
Лучше не создавать мапер каждый раз, а оформить его как бин @Component и заинжектить в наше dao

2023-06-08 04:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDaoImpl.java
> +        if (genre == null) {
В твоем случе `.orElse(null);`, с последующим `if` было лишним.
У тебя уже было то что нужно!

```
    @Override
    public Optional<Genre> findById(int id) {
        return jdbcTemplate.query("SELECT id_genre, name FROM genres WHERE id_genre=?", new GenreMapper(), id)
                                  .stream()
                                  .findAny();
    }
```

2023-06-08 04:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDaoImpl.java
> +        for (Genre genre : genres) {
Вот тут тоже цикл и вставка по одному, вместо одного запроса для всех жанров.
Но на первом этапе, не критично, я думаю.

2023-06-09 07:50 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDaoImpl.java
> +                        new GenreMapper(), id)
Оформила все маперы как бины и заинжектила в dao

2023-06-09 07:51 UTC, BiryulevaIrina commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDaoImpl.java
> +        if (genre == null) {
Проработала код в дао во всех методах findById

2023-06-09 07:53 UTC, merged